### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by Ronttikasa** [petrioski/tiralabra2022#1]
Projekti ladattu 12.6. n. klo 19

Projekti näyttää olevan oikein hyvällä mallilla. Koodi kääntyy ja peli on selkeä käyttää. Pelasin reilut parikymmentä tasaista kierrosta tietokonetta vastaan ja ainakaan ihan naurettavan helppoa sen voittaminen ei ole. Pelin käyttöliittymä on yksinkertaisen selkeä ja komennot toimivat. Ohjetekstin mukaan peli tosin loppuu kun jompikumpi pelaajista saa kolme pistettä, kun kolmen pisteen kohdalla peli ei päättynyt ajattelin sen tarkoittavan kolmen pisteen _eroa_, mutta koodista selvisi että peli päättyykin 30 pisteen saavuttamiseen.

Koodi on siistiä ja selkeälukuista ja tyylikkäästi jaettu luokkiin ja metodeihin. Paikoitellen käytössä on sen verran lyhennettyjä muuttujannimiä että ensilukemalta ne eivät ole ehkä maailman selkeimpiä, mutta mitään erityisen kryptisesti nimettyä en myöskään huomannut.

Tällä hetkellä koodissa on joitakin piiloon kommentoituja metodeja ja koodinpätkiä sekä muita docstringin ulkopuolisia kommentteja, jotka eivät ole hyvän tyylin mukaisia, mutta nämä liittyvät varmaankin tuleviin ominaisuuksiin tai muihin vielä kesken oleviin muutoksiin.

Testit menevät läpi ja testaavat nähdäkseni järkeviä asioita, ja koodin testikattavuus on hyvä. Hyvää työtä!

**Comment by petrioski** [comment]
Kiitos palautteesta. Korjaukset tehty. Hyvää loppukesää!
