### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by zmejka** [petrioski/tiralabra2022#2]
Ohjelma ladattu 14.6.2022 klo 18:50.

Hyvin mielenkiintoinen ja hauska projekti. Ohjelma toimii oikein ja tekstikäyttöliittymä on selkeä. Ohjelman rakenne on jaettu pakkauksiin asianmukaisesti. Metodien ja muuttujien nimet ovat pääosin kuvaavia ja johdonmukaisia. Koodia on kommentoitu hyvin, mutta joistain metodeista kommentit vielä puuttuvat. Koodissa on vielä jonkin verran pois kommentoitua koodia ja käyttämättömiä import käskyjä. 

Markovin ketjujen periaate ei ollut minulle ennestään tuttu, mutta ainakin ensimmäisen asteen ketju näyttäisi toimivan oikein. Olen pelannut peliä muutamia kertoja ja AI ei ollut helppo voittaa. Taktikoimalla peli päätyi melkein aina tasapeliin. Huomasin kuitenkin, että pelin voi saada tavallaan luuppiin, jolloin joka toinen kierros on tasapeli ja joka toinen pelaaja voittaa. Esimerkiksi, jos tasapelikierroksella tulos oli Rock-Rock, pelaaja pelasi Paper ja AI Rock. Kun pelaaja pelaa uudestaan Rock, suntyi tilanne,  jossa seuraavat kierrokset meni R-R, P-R, R-R, P-R jne kunnes pelaaja voittaa. Tässä tapauksessa peli selkeästi otti huomioon ainoastaan edellisen kierroksen. Olisi hyvä, jos pelin lopuksi voisi tulostaa siitä lyhyen raportin kuinka monta  tasapelia on tullut ja minkä asteen Markovin ketjuja on pelissä käytetty.

Ladatun ohjelmaversion testikattavuus on ollut 100%, mikä on erinomaista.

Projekti on tässä vaiheessa toteutettu hyvin. Hyvää työtä!

**Comment by petrioski** [comment]
Kiitos palautteesta. Korjaukset tehty. Hyvää loppukesää!

**Comment by petrioski** [comment]
Kiitos palautteesta. Korjaukset tehty. Hyvää loppukesää!
